#POST https://sap-ai-sql.azurewebsites.net/api/prompt
POST http://localhost:7071/api/prompt
content-type: application/json

{ "prompt": "What is the monthly average of the payments over the year 2019?" }